encoding:         UTF-8
title:            轻薄
description:      A responsive Jekyll theme with modern tendencies from designer Michael Rose.
disqus_shortname: qingbob
#Comment out url when working locally to resolve base urls correctly
url:              http://qingbob.com
gems: [jekyll-paginate] #
paginate: 10 #
paginate_path: "page:num" #
# Owner/author information
owner:
  name:           李翌
  avatar:         avatar.jpg
  bio:            "百度前端工程师，现居住在北京"
  email:          liguangyi08@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         hh54188
  weibo:          qinbob
  stackexchange:  
  linkedin:       
  instagram:        
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Background image to be tiled on all pages
background: ps_neutral.png

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-38061225-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: 购买《高性能响应式Web开发实战》
    external: true
    url: http://www.epubit.com.cn/book/details/4156
  - title: 项目
    url: /project
  - title: 订阅
    url: /feed.xml

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
# pygments:    true #
# highlighter: pygments 
highlighter: rouge #
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 10

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
